version: '3.8'

services:
  couchdb:
    image: couchdb:3.4.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=devpassword
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data: