services:
  - type: web
    name: in-between-api
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: docker-compose up -d couchdb && npm install
    startCommand: docker-compose up -d couchdb && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: COUCHDB_PASSWORD
        generateValue: true
      - key: COUCHDB_URL
        value: http://admin:${COUCHDB_PASSWORD}@localhost:5984