name: Build and Deploy - Web - Capgo

on:
  push:
    branches:
      - main
    paths:
      - 'web/src/**'
      - 'web/public/**'
      - 'web/package.json'
      - 'web/vite.config.js'
  workflow_dispatch:

jobs:
  deploy-ota:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Install dependencies
        run: |
          cd web
          npm ci

      - name: Build web app
        run: |
          cd web
          npm run build

      - name: Upload to Capgo
        env:
          CAPGO_API_KEY: ${{ secrets.CAPGO_API_KEY }}
        run: |
          cd web
          npx @capgo/cli bundle upload --bundle ${{ github.sha }} --channel production --apikey "$CAPGO_API_KEY"

      - name: Deploy summary
        run: |
          echo "✅ OTA update deployed to Capgo!"
          echo "📱 Users will receive this update automatically"
          echo "🔖 Version: ${{ github.sha }}"
