name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache-dependency-path: 'web/package-lock.json'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          cd web
          npm install
      
      - name: Build web app
        env:
          API_URL: ${{ vars.API_URL }}
        run: |
          cd web
          # Create .env.production file with environment variables
          echo "VITE_API_URL=${API_URL}" > .env.production
          echo "VITE_SOCKET_URL=${API_URL}" >> .env.production
          # Build the app
          npm run build
      
      # Create a CNAME file for the custom domain
      - name: Create CNAME file
        run: echo "in-between.live" > web/dist/CNAME
      
      # Copy index.html to 404.html for SPA routing
      - name: Create 404 page
        run: cp web/dist/index.html web/dist/404.html
      
      # Create .nojekyll file to prevent Jekyll processing
      - name: Create .nojekyll file
        run: touch web/dist/.nojekyll
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web/dist
          branch: gh-pages
          clean: true
          token: ${{ github.token }}
